import { makeStyles } from "@material-ui/core/styles";

export const useStyles = makeStyles((theme) => ({
    MarketsPage: {},
    Sidebar: {},
    MarketDetails: {},
    Cat: {
        color: "#6D8096",
        fontFamily: "Poppins",
        fontSize: "18px",
        letterSpacing: "0",
        lineHeight: "24px",
        marginBottom: "8px",
    },
    Title: {
        color: "#171D28",
        fontFamily: "Poppins",
        fontSize: "26px",
        fontWeight: 600,
        letterSpacing: "0",
        lineHeight: "32px",

        marginBottom: "24px",
    },
    Info: {
        padding: "24px",
        borderRadius: "16px",
        backgroundColor: "#FFFFFF",
        boxShadow: "0 0 20px 0 #E6EDFF",
        display: "flex",
        marginBottom: "24px",
        justifyContent: "space-between",
    },
    Info__Block: {},
    Info__BlockTitle: {
        color: "#8293A6",
        fontFamily: "Poppins",
        fontSize: "14px",
        letterSpacing: "0",
        lineHeight: "24px",
        marginBottom: "4px",
    },
    Info__BlockValue: {
        color: "#4E5D6D",
        fontFamily: "Poppins",
        fontSize: "14px",
        fontWeight: 600,
        letterSpacing: "0",
        lineHeight: "24px",
    },
    Graph: {
        padding: "24px",
        borderRadius: "16px",
        backgroundColor: "#FFFFFF",
        boxShadow: "0 0 20px 0 #E6EDFF",
        marginBottom: "24px",
    },
    Graph__Header: {
        display: "flex",
        alignItems: "center",
        marginBottom: "16px",
    },
    Graph__HeaderTitle: {
        marginRight: "auto",
        color: "#3F4A57",
        fontFamily: "Poppins",
        fontSize: "14px",
        fontWeight: 600,
        letterSpacing: "0",
        lineHeight: "24px",
    },
    Graph__HeaderNav: {
        display: "flex",
        alignItems: "center",
    },
    Graph__HeaderNavOption: {
        fontSize: "14px",
        fontWeight: 500,
        letterSpacing: "0",
        lineHeight: "32px",
        textAlign: "center",
        borderRadius: "8px",
        backgroundColor: "#EDEFF4",
        padding: "0 12px",
        marginLeft: "8px",
        color: "#8293A6",
        transition: "0.2s all",
        cursor: "pointer",
        "&:hover": {
            backgroundColor: "#004BFF",
            color: "#FFFFFF",
        },
    },
    Graph__HeaderNavOption__Selected: {
        backgroundColor: "#004BFF",
        color: "#FFFFFF",
    },
    Graph__Deatils: {},

    Outcome: {
        padding: "24px",
        borderRadius: "16px",
        backgroundColor: "#FFFFFF",
        boxShadow: "0 0 20px 0 #E6EDFF",
        marginBottom: "24px",
    },
    Outcome__Header: {
        color: "#3F4A57",
        fontFamily: "Poppins",
        fontSize: "14px",
        fontWeight: 600,
        letterSpacing: "0",
        lineHeight: "24px",
        marginBottom: "16px",
    },
    Outcome__Details: {
        display: "flex",
        '&>div' : {
            width: "calc(100% - 24px)",
            "&:first-child": {
                marginRight: "48px",
            },
        }
    },
    MarketPositions: {
        padding: "24px",
        borderRadius: "16px",
        backgroundColor: "#FFFFFF",
        boxShadow: "0 0 20px 0 #E6EDFF",
        marginBottom: "24px",
    },
    MarketPositions__Header: {
        color: "#3F4A57",
        fontFamily: "Poppins",
        fontSize: "14px",
        fontWeight: 600,
        letterSpacing: "0",
        lineHeight: "24px",
        marginBottom: "16px",
    },
    MarketPositions__Details: {},
    MarketPosition__Block: {
        display: "flex",
        alignItems: "center",
        borderBottom: "1px solid #EDEFF4",
        padding: "16px 0",
        "& span:first-child": {
            marginRight: "auto",
            color: "#8293A6",
            fontSize: "14px",
            letterSpacing: "0",
            lineHeight: "24px",
        },
        "& span:last-child": {
            color: "#4E5D6D",
            fontSize: "14px",
            fontWeight: 600,
            letterSpacing: "0",
            lineHeight: "24px",
            textAlign: "right",
        },
        "&:first-child": {
            paddingTop: "0",
        },
        "&:last-child": {
            borderBottom: "none",
        },
    },

    About: {
        padding: "24px",
        borderRadius: "16px",
        backgroundColor: "#FFFFFF",
        boxShadow: "0 0 20px 0 #E6EDFF",
        marginBottom: "24px",
    },
    About__Header: {
        color: "#3F4A57",
        fontFamily: "Poppins",
        fontSize: "14px",
        fontWeight: 600,
        letterSpacing: "0",
        lineHeight: "24px",
        marginBottom: "16px",
    },
    About__Details: {
        color: "#8293A6",
        fontSize: "14px",
        letterSpacing: "0",
        lineHeight: "24px",
    },

    Resolution: {
        padding: "24px",
        borderRadius: "16px",
        backgroundColor: "#E9EAFF",
        marginBottom: "24px",
    },
    Resolution__Header: {
        color: "#6D8096",
        fontSize: "14px",
        letterSpacing: "0",
        lineHeight: "24px",
        marginBottom: "8px",
    },
    Resolution__Details: {},
    ResolutionLink: {
        color: "#0042FF",
        fontSize: "12px",
        letterSpacing: "0",
        lineHeight: "24px",
    },
    MarketSidebar__AddLiquidity: {
        textAlign: 'center',
        marginBottom: '24px',
        '&>button': {
            marginRight: '10px',
            '&:last-child': {
                marginRight: 0,
            }
        }
    },
    MarketSidebar__AddLiquidityBtn: {
        //height: 'auto',
        //paddingLeft: '40px',
        //paddingRight: '40px',
    },
    MarketSidebar__AddLiquidityBtnInner: {
        flexWrap: 'wrap'
    },
    MarketSidebar__AddLiquidityApprove: {
        flex: 1,
        fontSize: '10px'
    },
    BuySellWidget: {
        borderRadius: "16px",
        backgroundColor: "#FFFFFF",
        boxShadow: "0 0 20px 0 #E6EDFF",
        padding: "24px",
    },
    BuySellWidget__Nav: {
        display: 'flex',
        alignItems: 'center',
        marginBottom: '24px',
        '& >div': {
            paddingBottom: '15px',
            width: '50%',
            color: "#2B3540",
            fontSize: "14px",
            fontWeight: 600,
            letterSpacing: "0",
            lineHeight: "24px",
            textAlign: "center",
            borderBottom: '2px solid #EDEFF4',
            cursor: 'pointer',
            transition: '0.2s all',
            '&[data-selected="true"], &:hover': {
                borderBottom: '2px solid #0051FF',
            }
        }
    },
    BuySellWidget__Options: {
        marginBottom: '16.5px',
        paddingBottom: '16.5px',
        borderBottom: '1px solid #EDEFF4'
    },
    Options__Header: {
        color: "#4E5D6D",
        fontSize: "14px",
        letterSpacing: "0",
        lineHeight: "24px",
        marginBottom: '8px'
    },
    BuySellWidgetAmount: {
        marginBottom: "16px",
    },
    BuySellWidgetAmount__Header: {
        color: "#4E5D6D",
        fontFamily: "Poppins",
        fontSize: "14px",
        letterSpacing: "0",
        lineHeight: "24px",
        marginBottom: "8px",
    },
    BuySellWidgetAmount__InputWrap: {
        position: "relative",
        "& input": {
            border: "1px solid #D2D9E1",
            borderRadius: "8px",
            backgroundColor: "#FFFFFF",
            display: "block",
            width: "100%",
            color: "#99A6B7",
            fontSize: "14px",
            letterSpacing: "0",
            lineHeight: "14px",
            padding: "16.5px",
            outline: "none",
            boxShadow: "none",
        },
        "& div": {
            color: "#004BFF",
            fontSize: "14px",
            fontWeight: 500,
            letterSpacing: "0",
            lineHeight: "14px",
            paddingBottom: "1px",
            borderBottom: "2px solid #004BFF",
            position: "absolute",
            top: "50%",
            transform: "translateY(-50%)",
            right: "10px",
            cursor: "pointer",
        },
    },
    BuySellWidgetInfo: {},
    BuySellWidgetInfo__Row: {
        display: "flex",
        alignItems: "center",
        padding: "16px 0",
        borderBottom: "1px solid #EDEFF4",
    },
    BuySellWidgetInfo__RowTitle: {
        color: "#8293A6",
        fontFamily: "Poppins",
        fontSize: "14px",
        letterSpacing: "0",
        lineHeight: "24px",
        marginRight: "auto",
    },
    BuySellWidgetInfo__RowValue: {
        color: "#4E5D6D",
        fontFamily: "Poppins",
        fontSize: "14px",
        fontWeight: 600,
        letterSpacing: "0",
        lineHeight: "24px",
        textAlign: "right",
    },
}));
