export const SmartContractsContextFunctions = {
  LOAD_WALLET_BALANCE_OF_TOKEN: 'LOAD_WALLET_BALANCE_OF_TOKEN',
  LOAD_WALLET_ALLOWANCE: 'LOAD_WALLET_ALLOWANCE',
  LOAD_OPTION_APPROVED_MARKET: 'LOAD_OPTION_APPROVED_MARKET',
  LOAD_OPTION_APPROVED_MARKET_CONTROLLER: 'LOAD_OPTION_APPROVED_MARKET_CONTROLLER',
  LOAD_MARKET_INFO: 'LOAD_MARKET_INFO',
  LOAD_MARKET_WALLET_DATA: 'LOAD_MARKET_WALLET_DATA',
  APPROVE_CONTRACT_TO_SPENDER: 'APPROVE_CONTRACT_TO_SPENDER',
  APPROVE_OPTION_TOKEN_TO_SPENDER: 'APPROVE_OPTION_TOKEN_TO_SPENDER',
};

export const formatAddress = (entry) => {
    return entry && entry.toLowerCase();
}
